services:
  postgres:
    container_name: postgres_db
    image: postgres:12.19-alpine3.20
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: thanh1509
      PGDATA: data/postgres
    volumes:
#      - db: data/postgres
      - type: tmpfs
        target: /var/data/postgres
    networks:
      - microservices-net
    ports:
      - "5432:5432"

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - type: tmpfs
        target: /var/data/postgres
    ports:
      - "5050:80"
    networks:
      - microservices-net
    restart: unless-stopped
networks:
  microservices-net:
    driver: bridge